# Generated by Codex on 2026-05-30

import re

from django.db import migrations, models


SALES_OFFICER = "SALES_OFFICER"
NIPPON_DOMAIN = "@nippon.test"
EMPLOYEE_CODE_PATTERN = r"^SO-[0-9]+$"


def normalize_existing_sales_officers(apps, _schema_editor):
    User = apps.get_model("accounts", "User")

    sales_officers = list(User.objects.filter(role=SALES_OFFICER).order_by("id"))
    used_codes = set()
    next_serial = 101

    for role, raw_code in User.objects.exclude(employee_code="").values_list("role", "employee_code"):
        code = (raw_code or "").strip().upper()
        match = re.fullmatch(EMPLOYEE_CODE_PATTERN, code)
        if match:
            if role != SALES_OFFICER:
                used_codes.add(code)
            next_serial = max(next_serial, int(code.split("-", 1)[1]) + 1)

    taken_emails = {
        (email or "").strip().lower(): pk
        for pk, email in User.objects.values_list("pk", "email")
        if email
    }
    taken_usernames = {
        (username or "").strip().lower(): pk
        for pk, username in User.objects.values_list("pk", "username")
        if username
    }

    for user in sales_officers:
        original_code = (user.employee_code or "").strip().upper()

        if re.fullmatch(EMPLOYEE_CODE_PATTERN, original_code) and original_code not in used_codes:
            code = original_code
        else:
            while f"SO-{next_serial}" in used_codes:
                next_serial += 1
            code = f"SO-{next_serial}"
            next_serial += 1

        used_codes.add(code)

        old_email = (user.email or "").strip().lower()
        owner_pk = taken_emails.get(old_email)
        if old_email.endswith(NIPPON_DOMAIN) and owner_pk in {None, user.pk}:
            email = old_email
        else:
            base = code.lower()
            email = f"{base}{NIPPON_DOMAIN}"
            suffix = 2
            while taken_emails.get(email) not in {None, user.pk}:
                email = f"{base}.{suffix}{NIPPON_DOMAIN}"
                suffix += 1

        taken_emails.pop(old_email, None)
        taken_emails[email] = user.pk

        username = email
        suffix = 2
        while taken_usernames.get(username) not in {None, user.pk}:
            local, domain = email.split("@", 1)
            username = f"{local}.{suffix}@{domain}"
            suffix += 1

        old_username = (user.username or "").strip().lower()
        taken_usernames.pop(old_username, None)
        taken_usernames[username] = user.pk

        user.email = email
        user.username = username
        user.employee_code = code
        user.save(update_fields=["email", "username", "employee_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_sales_officers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("employee_code",),
                condition=~models.Q(employee_code=""),
                name="unique_nonblank_employee_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(employee_code="")
                | models.Q(employee_code__regex=EMPLOYEE_CODE_PATTERN),
                name="employee_code_format_so_serial",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=~models.Q(role=SALES_OFFICER)
                | models.Q(email__iendswith=NIPPON_DOMAIN),
                name="sales_officer_email_nippon_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=~models.Q(role=SALES_OFFICER)
                | models.Q(employee_code__regex=EMPLOYEE_CODE_PATTERN),
                name="sales_officer_employee_code_required",
            ),
        ),
    ]
