# Generated by Django 5.2.14 on 2026-05-30 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_sold', models.PositiveIntegerField(default=0)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='inventory.carmodel')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.monthlysalesentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monthlysalesentry',
            constraint=models.UniqueConstraint(fields=('sales_officer', 'month', 'year'), name='unique_entry_per_officer_month'),
        ),
        migrations.AddConstraint(
            model_name='salesline',
            constraint=models.UniqueConstraint(fields=('entry', 'car_model'), name='unique_car_per_entry'),
        ),
    ]
