# Generated by Django 5.2.14 on 2026-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cars', models.PositiveIntegerField(help_text='Inclusive lower bound.')),
                ('max_cars', models.PositiveIntegerField(blank=True, help_text='Inclusive upper bound; NULL = open-ended.', null=True)),
                ('rate_per_car', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['min_cars'],
            },
        ),
    ]
